import { Theme, makeStyles, withStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles((theme: Theme) => ({
  displayNone: {
    display: "none",
  },
  loaderWrapper: {
    position: "fixed",
    zIndex: 99998,
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  modalRoot: {
    padding: "30px 35px",
    position: "fixed",
    width: "935px",
    background: "#282E4E",
    boxShadow: "0px 0px 30px rgba(55, 55, 79, 0.05)",
    borderRadius: "10px",
    textAlign: "center",
    zIndex: 99999,
    [theme.breakpoints.down(975)]: {
      minWidth: "calc(100% - 32px) !important",
      width: "calc(100% - 32px) !important",
      margin: "0px 50px",
    },
  },
  closeIcon: {
    position: "absolute",
    top: "30px",
    right: "30px",
    cursor: "pointer",
    backgroundColor: "#4a4f66",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "100%",
    width: "35px",
    height: "35px",
    "& i": {
      fontWeight: 100,
    },
  },
  title: {
    fontStyle: "normal",
    fontFamily: "Montserrat",
    fontWeight: 600,
    fontSize: "20px",
    lineHeight: "50px",
    color: "#FFFFFF",
  },
  mainContainer: {
    margin: "30px 0px 0px",
    backgroundColor: "#141b31",
    height: "435px",
    borderRadius: "12px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px 75px",
  },
  dragPartContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
  },
  uploadImgContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "80px",
    height: "80px",
    marginBottom: "55px",
  },
  uploadIcon: {
    width: "100%",
    height: "100%",
  },
  dragInfoContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  normalLetter: {
    color: "#96A1DB",
    fontSize: "18px",
    fontFamily: "Lato",
    lineHeight: "29px",
  },
  browserContainer: {},
  colorLetter: {
    fontSize: "18px",
    fontFamily: "Lato",
    lineHeight: "29px",
    cursor: "pointer",
    color: "#fb895a",
  },
  fileInput: {
    display: "none",
  },
  importantFunctionLink: {
    textAlign: "center",
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "18px",
    lineHeight: "29px",
    color: "#fb895a",
    position: "relative",
  },
  fileImport: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    cursor: "pointer ",
  },
}));
