import { Theme, makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles((theme: Theme) => ({
  root: {
    height: "calc(100vh - 120px)",
    display: "flex",
    flexFlow: "column nowrap",
    justifyContent: "center",
    position: "relative",
    overflow: "hidden",
    padding: "64px",
    backgroundColor: " #18141a",
    borderBottom: "1px solid #67637033",
  },
  itemContainer: {
    width: "1064px",
    maxWidth: "100% !important",
    marginLeft: "auto !important",
    marginRight: "auto !important",
  },
  title: {
    margin: "calc(2rem - 0.14286em) 0 1rem",
    position: "relative",
    fontSize: "40px",
    lineHeight: "48px",
    letterSpacing: ".4px",
    minHeight: "1em",
    color: "#fff",
    fontWeight: 500,
    fontStretch: "normal",
  },
  subtitle: {
    color: "#676370",
    marginBottom: "24px",
    marginTop: 0,
    position: "relative",
    fontWeight: 400,
    margin: "calc(2rem - .14286em) 0 1rem",
    fontSize: "20px",
    lineHeight: "28px",
    fontStyle: "normal",
  },
  hero_action: {
    width: "1064px",
    maxWidth: "100% !important",
    marginLeft: "auto !important",
    marginRight: "auto !important",
    marginTop: "16px",
    position: "relative",
    fontWeight: 400,
  },
  browsebtn: {
    backgroundColor: "#ff2d55",
    color: "#fff",
    padding: "13px 32px",
    borderRadius: "6px",
    fontSize: "13px",
    lineHeight: "18px",
    minWidth: "128px",
    fontStyle: "normal",
    fontStretch: "normal",
    letterSpacing: "normal",
    textTransform: "uppercase",
    fontFamily:
      'system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif',
    textAlign: "center",
    fontWeight: 600,
    cursor: "pointer",
    display: "inline-block",
    minHeight: "1em",
    outline: 0,
    border: "none",
    verticalAlign: "baseline",

    "&:hover": {
      backgroundColor: "#ff3d61",
      cursor: "pointer",
      transform: "translateY(-2px)",
      boxShadow: "0 3px 6px 0 rgb(0 0 0 / 6%)",
    },
  },
}));
