import { Theme, makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles((theme: Theme) => ({
  root: {
    height: "calc(100vh - 121px)",
    display: "flex",
    flexFlow: "column nowrap",
    justifyContent: "start",
    position: "relative",
    overflow: "hidden",
    backgroundColor: " #21263f",
    borderBottom: "1px solid #67637033",
    textAlign: "center",
  },
  itemContainer: {
    width: "1064px",
    maxWidth: "100% !important",
    marginLeft: "auto !important",
    marginRight: "auto !important",
  },
  title: {
    margin: "calc(2rem - 0.14286em) 0 1rem",
    position: "relative",
    fontSize: "45px",
    lineHeight: "48px",
    letterSpacing: ".4px",
    minHeight: "1em",
    color: "#fff",
    fontWeight: 600,
    fontStretch: "normal",
    marginTop: "20%",
  },
  subtitle: {
    color: "#96A1DB",
    marginBottom: "24px",
    marginTop: 0,
    position: "relative",
    fontWeight: 400,
    margin: "calc(2rem - .14286em) 0 1rem",
    fontSize: "18px",
    lineHeight: "28px",
    fontStyle: "normal",
  },
  hero_action: {
    maxWidth: "1064px",
    marginLeft: "auto !important",
    marginRight: "auto !important",
    marginTop: "16px",
    position: "relative",
    fontWeight: 400,
  },
  browsebtn: {
    background: "linear-gradient(90deg, #FF7C4C 20%, #FFB03A 101.82%)",
    color: "#fff",
    width: "190px",
    height: "45px",
    borderRadius: "25px",
    fontSize: "16px",
    lineHeight: "18px",
    minWidth: "128px",
    fontStretch: "normal",
    fontFamily:
      'system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif',
    textAlign: "center",
    fontWeight: 500,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    outline: 0,
    border: "none",
    textTransform: "none",
    "&:hover": {
      backgroundColor: "#ff3d61",
      cursor: "pointer",
      transform: "translateY(-2px)",
      boxShadow: "0 3px 6px 0 rgb(0 0 0 / 6%)",
    },
  },
  topleftTexture: {
    position: "absolute",
    top: "0px",
    width: "29%",
  },
  toprightTexture: {
    position: "absolute",
    top: "0px",
    right: "0px",
    width: "35%",
  },
  topEllipse1: {
    position: "absolute",
    top: "0px",
    left: "5%",
    width: "16%",
  },
  topEllipse2: {
    position: "absolute",
    top: "25%",
    left: "20%",
    width: "8%",
  },
  topEllipse3: {
    position: "absolute",
    top: "10%",
    right: "10%",
    width: "12%",
  },
}));
